userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

function run {
  if command -v $1 > /dev/null; then
    eval $@ &
  else
    echo "<ERR> '$1' failed!"
  fi
}

#run_or_err imwheel && imwheel
run redshift -l -16.68:-49.26
run urxvtd -q -o -f
run xbindkeys
run dunst
run xrdb -merge ~/.Xresources
run xset b off
run setxkbmap -layout us -variant intl
run xrandr --output DP1 --right-of eDP1 --auto --mode 3840x2160

exec i3
