# vim: filetype=zsh

export CODE=$HOME/code

if [[ "$(uname -s)" == "Darwin" ]]; then
  export CODE=$HOME/Code
fi

export CVS_RSH="ssh"
export CVSROOT="salazar@cvs.NetBSD.org:/cvsroot"
export ANONCVS="anoncvs@anoncvs.NetBSD.org:/cvsroot"

export CLICOLOR="YES"
export VISUAL=vim
export EDITOR=vim
export LESS="-RMIKC +Gg"
export PAGER=less

if [[ "$(uname -s)" == "Darwin" ]]; then
  eval $(/usr/libexec/path_helper)
  eval $(/opt/homebrew/bin/brew shellenv)
fi

if [[ "$(uname -s)" == "NetBSD" ]]; then
  export PATH="$PATH:/sbin:/usr/pkg/bin:/usr/pkg/sbin:/usr/X11R7/bin"
fi

export PATH="$PATH:$HOME/bin:$HOME/.bin:$HOME/.local/bin"

# Go
export GOPATH="$CODE/go"
export PATH="$PATH:$GOPATH/bin"

# Rust
export PATH="$PATH:$HOME/.cargo/bin"

# Ruby
if which rbenv &> /dev/null; then
  eval "$(rbenv init -)"
fi

# Python
if which pyenv &> /dev/null; then
  eval "$(pyenv init -)"
fi

# Luarocks
export PATH="$PATH:/opt/luarocks/bin"

export RESTY_PATH="/opt/openresty"

export PATH="$PATH:$RESTY_PATH/bin"
export PATH="$PATH:$RESTY_PATH/luajit/bin"

# Homebrew
export HOMEBREW_NO_AUTO_UPDATE=true
export HOMEBREW_MAKE_JOBS=$(( $(nproc 2> /dev/null || gnproc) + 1 ))

export LANG="en_US.UTF-8" export LC_CTYPE="en_US.UTF-8" export LC_ALL=""

gpg-agent --daemon
export SSH_AUTH_SOCK="$(gpgconf --list-dirs agent-ssh-socket)"

export MAIL=$HOME/mail
export CONF=$CODE/dotfiles
export ZSH=$CONF/dots/zsh
