# vim: filetype=zsh

# source util early for helper functions (os detection, path helpers, etc.)
source ${0:A:h}/zsh/functions/util 2>/dev/null || source $ZSH/functions/util 2>/dev/null

export CODE=$HOME/code

if is_macos; then
  export CODE=$HOME/Code
fi

export CVS_RSH="ssh"
export CVSROOT="gs@cvs.NetBSD.org:/cvsroot"
export ANONCVS="anoncvs@anoncvs.NetBSD.org:/cvsroot"

export CLICOLOR="YES"
export VISUAL=vim
export EDITOR=vim
export LESS="-RMIKC +Gg"
export PAGER=less

if is_macos; then
  eval $(/usr/libexec/path_helper)
  eval $(/opt/homebrew/bin/brew shellenv)
fi

if is_netbsd; then
  path_append /sbin
  path_append /usr/pkg/bin
  path_append /usr/pkg/sbin
  path_append /usr/X11R7/bin
fi

path_append "$HOME/bin"
path_append "$HOME/.bin"
path_append "$HOME/.local/bin"

# Go
export GOPATH="$CODE/go"
path_append "$GOPATH/bin"

# Rust
path_append "$HOME/.cargo/bin"

# Ruby
init_tool_env rbenv

# Python
init_tool_env pyenv

# Luarocks
path_append /opt/luarocks/bin

export RESTY_PATH="/opt/openresty"

path_append "$RESTY_PATH/bin"
path_append "$RESTY_PATH/luajit/bin"

# Homebrew
export HOMEBREW_NO_AUTO_UPDATE=true
export HOMEBREW_MAKE_JOBS=$(( $(nproc 2> /dev/null || gnproc) + 1 ))

export LANG="en_US.UTF-8" export LC_CTYPE="en_US.UTF-8" export LC_ALL=""

eval $(gpg-agent --daemon &>/dev/null)
export SSH_AUTH_SOCK="$(gpgconf --list-dirs agent-ssh-socket)"

export MAIL=$HOME/mail
export CONF=$CODE/dotfiles
