" Setup
set nocompatible
scriptencoding utf-8
filetype plugin on
filetype plugin indent on

" Backup
set swapfile
set dir=~/.vim/swap
set nobackup

" General
let os = substitute(system('uname'), "\n", "", "")

if os == "Darwin" || os == "Mac"
	set clipboard=unnamed
elseif os == "Linux"
	set clipboard=unnamedplus
endif

set mouse=a
set ttyfast
set splitright
set backspace=2
set colorcolumn=81
set showcmd
set number
set relativenumber
set title
set ruler
set nowrap
set textwidth=90
set spelllang=en_us,pt
set spell
set nofoldenable
set formatoptions+=w

" Search
set ignorecase
set smartcase
set noincsearch
set hlsearch

" Visual
set list
set listchars=eol:¬,tab:▸\ 
set hidden
set smarttab
set wildmenu
set showmatch
set autoindent
set cursorline
set smartindent
set noexpandtab
set shiftwidth=4
set softtabstop=0
set tabstop=4
set t_Co=256
set laststatus=1
set statusline=%f%h%m%r%=%{mode()},%c,%l/%L
set title
set titleold=""
set titlestring=vim
syntax on

set background=dark

colorscheme solarized

" Keybindings
cmap w!! w !sudo tee > /dev/null %
map <leader>n :noh<CR>

function! SearchVimwiki()
	let pattern = input('search pattern: ')
	execute 'VimwikiSearch '.pattern
endfunction
map <leader>ws :call SearchVimwiki()<CR>

let g:vimwiki_list = [{'syntax': 'markdown', 'ext': '.md', 'path': "~/wiki"}]
"let g:vimwiki_global_ext = 0
let g:vimwiki_folding=''

" Per-language indentation behavior
autocmd FileType c   setlocal cinoptions=t0 cindent
autocmd FileType sh  setlocal expandtab shiftwidth=2 tabstop=2
autocmd FileType lua setlocal expandtab shiftwidth=2 tabstop=2
autocmd FileType zsh setlocal expandtab shiftwidth=2 tabstop=2
autocmd FileType lex setlocal expandtab shiftwidth=4 tabstop=4
autocmd FileType tex setlocal expandtab shiftwidth=2 tabstop=2
autocmd FileType yacc setlocal expandtab shiftwidth=4 tabstop=4
autocmd FileType html setlocal expandtab shiftwidth=4 tabstop=4
autocmd FileType yaml setlocal expandtab shiftwidth=2 tabstop=2
autocmd FileType conf setlocal expandtab shiftwidth=2 tabstop=2
autocmd FileType perl setlocal expandtab shiftwidth=2 tabstop=2
autocmd FileType markdown setlocal expandtab shiftwidth=2 tabstop=2

let g:markdown_fold_override_foldtext = 0
let g:markdown_fold_style = 'nested'

let g:netrw_banner = 0
let g:netrw_liststyle = 3
let g:netrw_browse_split = 4
let g:netrw_altv = 1
let g:netrw_winsize = 25

